project:
  type: website

execute:
  freeze: auto

website:
  title: "ESCAP training on RAP"
  favicon: src/rap_hex.png
  repo-url: https://github.com/sergegoussev/ESCAP_RAP_class
  issue-url: https://github.com/sergegoussev/ESCAP_RAP_class/issues/new
  repo-actions: [issue, source]
  bread-crumbs: true
  search:
    show-item-context: true
    type: overlay
  sidebar:
    style: "docked"
    type: "dark"
    search: true
    logo: src/rap_hex.png
    logo-alt: logo
    logo-href: index.qmd
    border: true
    contents:
      - href: docs/index.qmd
        text: Overview
      - href: docs/teaching_materials/teaching.qmd
        text: Teaching materials
      - href: docs/process-mapping.qmd
        text: Mapping the process
      - href: docs/scraper_docs/scraper-docs.qmd
        text: Scraper docs
  page-footer: 
    left: "2024, ESCAP"
    right: 
      - icon: github
        href: https://github.com/sergegoussev/ESCAP_RAP_class
      - icon: globe 
        href: https://xtophe.notion.site/Web-Scraping-for-CPI-Training-c36b27c2ea6b4f02ad760069afaf6fb5

format:
  html:
    theme: cosmo
    css: docs/styles.css
    toc: true
    grid:
      sidebar-width: 350px
      body-width: 900px
      margin-width: 300px



