project:
  type: website

execute:
  freeze: auto

website:
  title: "ESCAP training on RAP"
  favicon: docs/images/favicon.drawio.svg
  repo-url: https://github.com/sergegoussev/ESCAP_RAP_class
  issue-url: https://github.com/sergegoussev/ESCAP_RAP_class/issues/new
  repo-actions: [issue, source]
  bread-crumbs: true
  page-navigation: true
  back-to-top-navigation: true
  search:
    location: sidebar
    type: overlay
  sidebar:
    style: "docked"
    type: "dark"
    search: true
    logo: docs/images/logo.drawio.svg
    logo-alt: logo
    logo-href: https://sergegoussev.github.io/ESCAP_RAP_class/docs/
    border: true
    contents:
      - href: docs/index.qmd
        text: Overview
      - section: 
        href: docs/teaching_materials/teaching.qmd
        contents: 
          - docs/teaching_materials/sept_11/sept_11_session.qmd
          - docs/teaching_materials/sept_18/sept_18_session.qmd
      - section:
      - href: docs/applying_rap/process-mapping.qmd
        contents:
          - notebooks/scraping_experiment.ipynb
      - section:
        href: docs/scraper_docs.qmd
        contents: docs/scraper_docs/*
  page-footer: 
    left: "2024, ESCAP"
    right: 
      - icon: github
        href: https://github.com/sergegoussev/ESCAP_RAP_class
      - icon: globe 
        href: https://xtophe.notion.site/Web-Scraping-for-CPI-Training-c36b27c2ea6b4f02ad760069afaf6fb5

format:
  html:
    theme: cosmo
    css: docs/styles.css
    toc: true
    grid:
      sidebar-width: 350px
      body-width: 900px
      margin-width: 300px



