project:
  type: website

execute:
  freeze: auto

website:
  title: "ESCAP training on RAP for consumer price statistics"
  favicon: src/rap_hex.png
  repo-url: https://github.com/sergegoussev/ESCAP_RAP_class
  issue-url: https://github.com/sergegoussev/ESCAP_RAP_class
  repo-actions: [issue, source]
  sidebar:
    search: true
    collapse-level: 1
    contents:
      - href: docs/index.qmd
        text: Overview
      - href: docs/teaching-material/material.qmd
        text: Teaching materials
      - href: docs/context.qmd
        text: Web scraping for CPI production - context

format:
  html:
    theme: cosmo
    css: docs/styles.css
    toc: true



