project:
  type: website

execute:
  freeze: auto

website:
  title: "ESCAP training on RAP"
  image: src/ESCAP_LOGO_OFFICIAL.png
  favicon: src/rap_hex.png
  repo-url: https://github.com/sergegoussev/ESCAP_RAP_class
  issue-url: https://github.com/sergegoussev/ESCAP_RAP_class/issues/new
  repo-actions: [issue, source]
  bread-crumbs: true
  search:
    show-item-context: true
    type: overlay
  navbar:
    background: light
    logo-alt: "Quarto logo."
    title: false
    collapse-below: lg
    left:
      - href: docs/index.qmd
        text: Overview
      - href: docs/teaching_materials/teaching.qmd
        text: Teaching materials
      - href: docs/process-mapping.qmd
        text: Mapping the process
      - href: docs/scraper-docs.qmd
        text: Scraper demo
format:
  html:
    theme: cosmo
    css: docs/styles.css
    toc: true
    grid:
      sidebar-width: 250px
      body-width: 900px
      margin-width: 300px



